# Generated by Django 6.0.6 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_availabel',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modify_date',
            new_name='modified_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
