# Generated by Django 6.0.6 on 2026-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
